version: "3.9"

services:
  product_service:
    build: ./product_service
    container_name: product_service
    ports:
      - "5001:5001"
    volumes:
      - ./product_service:/app
    environment:
      - FLASK_ENV=development

  order_service:
    build: ./order_service
    container_name: order_service
    ports:
      - "5002:5002"
    volumes:
      - ./order_service:/app
    environment:
      - PRODUCT_SERVICE_URL=http://product_service:5001
      - FLASK_ENV=development
    depends_on:
      - product_service

  frontend:
    build: ./frontend
    container_name: bakecart_frontend
    ports:
      - "8080:80"
    depends_on:
      - product_service
      - order_service
    environment:
      - PRODUCT_URL=http://product_service:5001/products
      - ORDER_URL=http://order_service:5002/orders
